### ISSUE TITLE
Patcho Not Found

### ISSUE THREAD

**Issue by ghost** [Defying/TweakPatcher#10]
PID 393 failed to act on a ping to dequeued before timing  out.

Failed to download patcho

**Comment by Defying** [comment]
is this issue still persisting?

ghostbin was down last night when you posted this, which is why it couldn't get the source for patcho

**Comment by ghost** [comment]
Just tried a few times and worked like a charm !! :)

Sent from my iPhone

On 11 Apr 2016, at 6:40 AM, Benjamin Weakley <notifications@github.com<mailto:notifications@github.com>> wrote:

is this issue still persisting?

ghostbin was down last night when you posted this, which is why it couldn't get the patcho

##

**Comment by Defying** [comment]
great! closing this issue
