### ISSUE TITLE
revisioning profile not found

### ISSUE THREAD

**Issue by Telesphoreo** [Defying/TweakPatcher#11]
title. i removed all the shit from keychain access but it keeps hanging on waiting for profile

**Comment by Defying** [comment]
did you follow the instructions above the line "Waiting on provisioning profile to be created..."?

**Comment by Telesphoreo** [comment]
yes

**Comment by Defying** [comment]
are you able to run that Xcode project you created on your iOS device?

**Comment by Telesphoreo** [comment]
Yes. I hit run and I just get the template for a master application. Also I am an apple developer

**Comment by Defying** [comment]
well if you have it on your iPhone, take that apps Bundle ID, and use it as an argument with the script like this this:

`./tweakpatcher.sh patch snapplus Snapchat.ipa BUNDLE_ID`

this should bypass asking you to make an Xcode project, and just use the provisioning profile you specified

**Comment by Telesphoreo** [comment]
I’ve done this. I did ./tweakpatcher.sh patch snapplus Snapchat.ipa com.toyopagroup

Also as an FYI I also did
./tweakpatcher.sh patch snapplus Snapchat.ipa com.toyopagroup.picaboo-D1666BA8-8D07-4EB6-9223-018EB160234A

**Comment by Defying** [comment]
that's strange.

have you tried making a new Xcode project with your own Product Name/Organization, running that on your iPhone, and passing that as an argument to the script?

assuming you're passing the correct Bundle ID, it should find it. 

all it's doing when it's showing "Waiting on provisioning profile" is constantly scanning `~/Library/MobileDevice/Provisioning Profiles` for a provisioning profile that matches the Bundle ID.

**Comment by Telesphoreo** [comment]
No. I’ve only used the string of text and the com.toy thing

**Comment by Telesphoreo** [comment]
Running it again I get this
[👻 ] Tweak Patcher for jailed iOS devices v0.2
[🔌 ] by Defying / @dvfying
[💻 ] GitHub: https://github.com/Defying/TweakPatcher

[💻 ] Xcode 7+ detected.

Syntax: /Users/user/Downloads/TweakPatcher-master/tweakpatcher.sh patch snapplus /path/to/decrypted.ipa <BUNDLE_ID>

SnapPlus for Snapchat is currently the only supported tweak.
More tweaks may be added in the future.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by Defying** [comment]
@PacksGamingHD post the exact command you used, seems that you messed up the syntax of it

**Comment by Telesphoreo** [comment]
Well removing the provisioning profiles stopped F.lux from working… no sleep…help

**Comment by Telesphoreo** [comment]
I did cd TweakPatcher-master and
./tweakpatcher.sh patch snapplus Snapchat.ipa in the directory where the files are

**Comment by Defying** [comment]
if you ran the command correctly, that shouldn't have came up.

it only shows the syntax usage message if you mistype something

**Comment by Telesphoreo** [comment]
No I didn’t get a syntax error. It said the Xcode 7+ was detected and started the download process, it detected my iOS device and gave me the project name and files

**Comment by iCraftSn0w** [comment]
Did you ever fix this issue? It's the same I'm encountering

**Comment by iCraftSn0w** [comment]
Ok I've found something that works!
I made a xcode project with just random bundle and product name.
Then I located the only Profile in /Libraray/Mobile Devices/Provissioning Profiles/ and then there should be a file in there copy the name of that file and then use that as the Bundle ID when running the script for snapplus

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
