### ISSUE TITLE
./tweakpatcher.sh: line 147: syntax error near unexpected token `}' ./tweakpatcher.sh: line 147: `}'

### ISSUE THREAD

**Issue by phantomkiller312** [Defying/TweakPatcher#12]
I'm using a VMware and I have completed most of the steps to getting snapchat "hacked" when i get to the command prompt i get this error, if i could get past this I would be able to finish the rest of it. Could anyone help?

**Comment by Defying** [comment]
what is the script doing right before this happens?

**Comment by phantomkiller312** [comment]
It's doing everything it's supposed to, it starts up the process, but then comes to this error

**Comment by Defying** [comment]
have you tried redownloading the script off GitHub?

that shouldn't be happening

**Comment by phantomkiller312** [comment]
Um no, so re download the zip file??

**Comment by Defying** [comment]
@phantomkiller312 yes

**Comment by phantomkiller312** [comment]
@defying so you where right, that worked now it says that no iPhone can be found, how do I correct that??

**Comment by Defying** [comment]
@phantomkiller312 do you have iTunes Wi-Fi Sync enabled?

**Comment by phantomkiller312** [comment]
@defying I'm not sure where do I go to turn it off?

**Comment by Defying** [comment]
@phantomkiller312 go to your device in iTunes, scroll down. is "Sync with this iPhone over Wi-Fi" enabled? if so, disable it

**Comment by phantomkiller312** [comment]
@defying it's not turned on, what now?

**Comment by Defying** [comment]
whats the output of `./bin/ios-deploy -c -W` ?

(make sure you're in the tweakpatcher directory)

**Comment by phantomkiller312** [comment]
@defying all it says is waiting up to 5 seconds for iOS device to be connected, then does nothing

**Comment by Defying** [comment]
what iPhone do you have?

**Comment by phantomkiller312** [comment]
@defying an iPhone 6s

**Comment by phantomkiller312** [comment]
@defying is there something that I need to do to the phone?

**Comment by phantomkiller312** [comment]
@ defying an iPhone 6s

**Comment by phantomkiller312** [comment]
@defying iPhone 6s

**Comment by Defying** [comment]
closing this as this issue has been resolved
