### ISSUE TITLE
Stuck at "[📥 ] Downloading libuasharedtools"

### ISSUE THREAD

**Issue by rqchetvision** [Defying/TweakPatcher#13]

**Comment by Defying** [comment]
is it still getting stuck there?

**Comment by James126788** [comment]
Yea mine does this as well is there a fix

**Comment by rqchetvision** [comment]
It will work! It just takes forever, trust me. Just let it sit.

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
