### ISSUE TITLE
❌ ] Failed to read Documents/container-uuid

### ISSUE THREAD

**Issue by goldenboy362** [Defying/TweakPatcher#15]
Idk what to do after this, it says disable wifi then do something else but it's not being specific please help asoon as possible

**Comment by Defying** [comment]
post your tweakpatcher.log

**Comment by gbuena22** [comment]
ive deleted the app on the phone.

Followed the steps about 4 times.
it downloads and then my snap opens and crashed.
not giving me enough time to press enter in terminal.
it cant find container UUID
![screen shot 2016-04-11 at 5 07 38 pm](https://cloud.githubusercontent.com/assets/18405825/14442468/ee190df6-0007-11e6-8024-443f18c0da78.png)

[tweakpatcher copy.txt](https://github.com/Defying/TweakPatcher/files/213877/tweakpatcher.copy.txt)

**Comment by matty99** [comment]
I'm having this same exact problem, i get the same errors and the app keeps crashing after i verify it in the settings on my phone

**Comment by WolfTitan** [comment]
Same problem

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
