### ISSUE TITLE
failed to install snapchat.ipa to iOS device

### ISSUE THREAD

**Issue by mohammedfpatel** [Defying/TweakPatcher#16]
please help i really want this hack. all my certificates are not expired my deployment target is correct everything is correct but it still doesn't work

**Comment by liudayu** [comment]
At least you can provide us some useful information like the installation log so we could help you get it solved asap??

**Comment by Defying** [comment]
please post your tweakpatcher.log

**Comment by faejr** [comment]
This is what's bothering me:
`ios-deploy[11568:1220608] [ !! ] Error 0xe80000be: unknown. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)`

Edit: It appears the application simply never got removed from my phone when I first thought I had it removed, my apologies for hijacking.

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
