### ISSUE TITLE
My iPhone won't connect

### ISSUE THREAD

**Issue by phantomkiller312** [Defying/TweakPatcher#17]
It says looking for iPhone in 5 seconds, then does nothing afterward, I have an iPhone 6s, any help?

**Comment by Defying** [comment]
so, the [ios-deploy](https://github.com/phonegap/ios-deploy) utility isn't able to detect your device for whatever reason that I'm not aware of.

from what I can tell, nothing in my script should be causing this as all my script is doing is downloading the source for ios-deploy, and building it.

**Comment by phantomkiller312** [comment]
@defying so basically I'm out of luck?

**Comment by gbuena22** [comment]
I had the same issue, on my mac.
I turn off the VM and connected my iphone directly to the back of the imac.
ran the .sh 
again and it worked!!

hope that helps.

**Comment by phantomkiller312** [comment]
@gbuena22 I've tried it, still doesn't work thanks for trying tho :/

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
