### ISSUE TITLE
❌ ] Failed to sign Snapchat.app with entitlements.xml. Check tweakpatcher.log for more information.

### ISSUE THREAD

**Issue by carsenlawrence** [Defying/TweakPatcher#18]
i have done everything. reset it, deleted certificates, did the whole process multiple times and i always get this error.

**Comment by carsenlawrence** [comment]
http://pastebin.com/wmVaxZQy

heres my tweakpatcher.log

**Comment by carsenlawrence** [comment]
http://pastebin.com/AsSjf1Hr

this is my tweakpatcher.log

**Comment by Defying** [comment]
from your log:

```
[✒️ ] Codesigning .dylib dependencies with certificate ""
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
: no identity found
```

it appears you're missing an iPhone Developer certificate

**Comment by carsenlawrence** [comment]
how do i get that?

**Comment by Defying** [comment]
@carsenlawrence try this: https://www.youtube.com/watch?v=MDhXQ33Gqzg

**Comment by carsenlawrence** [comment]
THANK YOU SO MUCH! now that this is all installed can i delete the files and delete xcode and everything i installed to clear up room on my computer?

**Comment by Defying** [comment]
you can, but I would only do it if you _really_ need the space. 

if you ever want to update Snapchat/SnapPlus, or possibly install new tweaks in the future, you'll need Xcode again

anyways, closing this issue now that it's been resolved.
