### ISSUE TITLE
Error Finding Container UUID!

### ISSUE THREAD

**Issue by WeWin55** [Defying/TweakPatcher#2]
Hi Developer, first of all well done!!
First ive got a problem installing the patched ipa, the app is installed fine and ive got the twitter notification from snap++, but no snap settings.

Terminal Output:

[🔎 ] Finding Container UUID
cat: /Users/XXUSERXX/Desktop/Snapchat_snaps/TweakPatcher-master/Documents/container-uuid: No such file or directory
[❌ ] Failed to read Documents/container-uuid

Tweakpatcher.log:

[100%] Installed package snapplus-patched.ipa
[📱 ] Open Snapchat on your iOS device!
You may need to "Trust" your Apple ID in Settings/General/Device Management.
[🔎 ] Finding Container UUID
[....] Waiting for iOS device to be connected
[....] Using (9635f32c402dedbfebe7eb6b653be3aba2adefa0ss).
[❌ ] Failed to read Documents/container-uuid

And my question is, how can i rename the patched snapchat from Snapchat to for example Snap+?

Thanks in Advance!

**Comment by Jedeyeboba** [comment]
You could always resign the IPA using iOS App Signer to change the display name.

**Comment by Defying** [comment]
@WeWin55, after it fails, is there a Documents/container-uuid in the TweakPatcher-master directory?

**Comment by WeWin55** [comment]
@Jedeyeboba thanks, i will look into it.

@Defying no only the Documents folder but hes empty even looking with ls -la

**Comment by Defying** [comment]
@WeWin55 just to clarify, do you have your iPhone connected to your Mac via USB or Wi-Fi?

**Comment by WeWin55** [comment]
via USB

**Comment by Defying** [comment]
I see. Someone told me they fixed this issue by turning on Airplane Mode, and using USB. Maybe you should try that (even though you're already using USB)?

**Comment by Defying** [comment]
also, can you run `./bin/ios-deploy -1 com.toyopagroup.picaboo --list` and post the output? thanks

**Comment by WeWin55** [comment]
With airplane mode off the Documents folder is also empty

Output:

Moritzs-Mac-Pro:TweakPatcher-master $ ./bin/ios-deploy -1 com.toyopagroup.picaboo --list
[....] Waiting for iOS device to be connected
[....] Using (9635f32c402dedbfebe7eb6b653be3aba2adefa0ss).

**Comment by Defying** [comment]
I wonder if this is a bug with ios-deploy. It should outputting the type of device and the name of it before the UUID.

**Comment by WeWin55** [comment]
hm thats not good. Can i test it in a way?

**Comment by WeWin55** [comment]
Okay ive got it!!

Moritzs-Mac-Pro:TweakPatcher-master$ ./bin/ios-deploy -1 com.toyopagroup.picaboo -W --list
[....] Waiting for iOS device to be connected
[....] Using iPhone 6 (GSM) 'iPhone7,2' (9635f32c402dedbfebe7eb6b653be3aba2adefa0).
//
/Documents/
/Documents/container-uuid
/Documents/dnsdat.plist
/Documents/proxydat.plist
/Documents/studySettings.plist
/Library/
/Library/Application Support/
/Library/Application Support/FlurryFiles/
/Library/Application Support/FlurryFiles/.flurryStored342887972_125.archive
/Library/Application Support/FlurryFiles/3A76A34C-8010-4231-ACD3-9E64485BB7B2
/Library/Application Support/FlurryFiles/DAA85A0A-A36B-44CE-AA4F-BE874F753C01
/Library/Application Support/FlurryFiles/DF106E49-13C2-4747-9A1B-A973C4108815
/Library/Application Support/FlurryFiles/FlurrySenderIndex.info
/Library/Caches/
/Library/Caches/com.toyopagroup.picaboo/
/Library/Caches/com.tumblr.TMDiskCache.stories.data/
/Library/Preferences/
/Library/Preferences/com.toyopagroup.picaboo.plist
/Library/com.amplitude.archiveDict.blizzard
/Library/com.amplitude.plist.blizzard
/tmp/

**Comment by Defying** [comment]
What did you do differently? Does the script work properly now?

**Comment by WeWin55** [comment]
Hm i looked at the options for ios-deploy and added -W that stands for ignoring Wifi Devices.
im looking right know at your script to add this argument and test it

**Comment by WeWin55** [comment]
I dont see where you use ios-deploy in your script, just downloading it.
Is there another way to add the -W argument to your script?

**Comment by Defying** [comment]
look for `$IOSDEPLOY`

**Comment by WeWin55** [comment]
wow thats very often in your script. I dont know where to add the -W

**Comment by Defying** [comment]
If you wait a few minutes, I'm about to update the script with it.

**Comment by WeWin55** [comment]
yeah i wait, thank you!

**Comment by Defying** [comment]
@WeWin55 updated it: https://github.com/Defying/TweakPatcher/archive/master.zip

see if this fixes your issue

**Comment by WeWin55** [comment]
Hm the -W argument didnt worked..

Log output:

ls: .temp/Payload/Snapchat.app/PlugIns/com._/com._: No such file or directory
ls: .temp/Payload/Snapchat.app/PlugIns/com._: No such file or directory
ls: .temp/Payload/Snapchat.app/Frameworks/_: No such file or directory
[📲 ] Installing snapplus-patched.ipa to iOS device
2016-04-09 00:05:28.541 ios-deploy[14189:2903941] [ !! ] Can't access app path '-W' : No such file or directory
[❌ ] Failed to install Snapchat.ipa to iOS device. Check tweakpatcher.log for more information.

**Comment by WeWin55** [comment]
_*_in which line added you the -W?
*__
edit: seen it

**Comment by Defying** [comment]
oops

updated it again, try it now

**Comment by WeWin55** [comment]
okay downloading master.zip, trying now :)

**Comment by WeWin55** [comment]
Hm the script went through, but theres no snap+ in my snapchat..

**Comment by Defying** [comment]
whats the output from terminal look like?

**Comment by WeWin55** [comment]
Script output:

🔎 ] Finding Container UUID
[🔎 ] Found Container UUID: 127A9598-ECE5-4100-9E2D-EE5E5F4B4A56
[🔎 ] 127A9598-ECE5-4100-9E2D-EE5E5F4B4A56 -> 31323741393539382d454345352d343130302d394532442d454535453546344234413536
[💉 ] Patching AppPlus.dylib with new Container UUID
[✒️ ] Codesigning AppPlus.dylib with "iPhone Developer: (963sv9al93)"
[📲 ] Copying AppPlus.dylib to com.toyopagroup.picaboo/Documents
[📲 ] Copying AppPlusSC/APResources.bundle to com.toyopagroup.picaboo/Documents

[🎉 ] SnapPlus installed! Please force close and reopen Snapchat.

[♻️ ] If you ever want to run this patcher again for the same app/tweak,
you can reuse the same provisioning profile to keep things clean.

Open ProvisioningProfile.txt for more information.

**Comment by Defying** [comment]
did you reopen snapchat?

**Comment by WeWin55** [comment]
hm just wait :D

**Comment by WeWin55** [comment]
fuck ok I feel silly now :D

Thanks anyway! :)

**Comment by Defying** [comment]
did it work? :D

**Comment by WeWin55** [comment]
Yes and its awesome! Wow thank you for making this nice script to patch snap+ into Snapchat on non-jailbroken iPhones! :)

**Comment by Defying** [comment]
glad to hear it worked.

a few other people were having this issue as well, I'll see if it fixed it for them. :+1:

**Comment by WeWin55** [comment]
Nice to hear! 👍
