### ISSUE TITLE
entitlements.xml

### ISSUE THREAD

**Issue by lilmaticc97** [Defying/TweakPatcher#20]
Hey there, I tried installing SnapPlus and its just not possible. is having ios 9.3.1 an issue because it wont go beyond entitlements.xml error.... see tweakpatcher.log nothing beyond that is possible. Please help

**Comment by Defying** [comment]
post your tweakpatcher.log

**Comment by cougs86** [comment]
@Defying can you help me? also i tried to attach mine but it doesn't accept .log

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
