### ISSUE TITLE
"Failed to build patcho"

### ISSUE THREAD

**Issue by bspears1** [Defying/TweakPatcher#21]
Ive tried this a million times. Ive deleted all certificates and I've started from the beginning and I don't know what else to try. It tells me "Failed to build patch" every time.

**Comment by chhaugen** [comment]
It could be that the problem is that it did not download patcho correctly, since ghostbin.com is down, where it downloads patcho from.
(https://ghostbin.com/paste/ejjej/raw)

**Comment by Defying** [comment]
try downloading TweakPatcher again, I've changed the source location for patcho (ghostbin kept going down).

if it still fails to build, post your tweakpatcher.log

**Comment by menito21** [comment]
Hey defying what other source did you use? im having the same problem

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
