### ISSUE TITLE
Xcode doesn't show fix issue for provisional files

### ISSUE THREAD

**Issue by qofa** [Defying/TweakPatcher#23]
After Terminal creates the ID and you put it in Xcode the option to fix the issue of "No matching provisioning files found" is not existent.

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
