### ISSUE TITLE
"Failed to build patcho. Check tweakpatcher.log for more information."

### ISSUE THREAD

**Issue by Randoman24** [Defying/TweakPatcher#24]
It keeps doing this, please help!

**Comment by Defying** [comment]
Have you downloaded the script in the last hour? This should be fixed.

On Monday, April 11, 2016, Randoman24 notifications@github.com wrote:

> It keeps doing this, please help!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Defying/TweakPatcher/issues/24

## 
- Benjamin Weakley

**Comment by Randoman24** [comment]
I just re downloaded it and it works, thanks
