### ISSUE TITLE
[❌ ] Failed to sign Snapchat.app with entitlements.xml. Check tweakpatcher.log for more information.

### ISSUE THREAD

**Issue by Hittiz** [Defying/TweakPatcher#25]
how can i fix that?

**Comment by Defying** [comment]
post your tweakpatcher.log

**Comment by adrianFut44** [comment]
I have the same problem here is my tweakpatcher.log 
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/214439/tweakpatcher.log.zip)

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
