### ISSUE TITLE
[❌ ] Failed to sign Snapchat.app with entitlements.xml.

### ISSUE THREAD

**Issue by cougs86** [Defying/TweakPatcher#26]
hey I'm having a problem with this [❌ ] Failed to sign Snapchat.app with entitlements.xml. please help, i know i have to put in my tweakpatcher.log but where do i get that?

**Comment by cougs86** [comment]
[✒️ ] Codesigning Plugins and Frameworks with certificate ""
ls: .temp/Payload/Snapchat.app/PlugIns/com._/com._: No such file or directory
ls: .temp/Payload/Snapchat.app/PlugIns/com._: No such file or directory
ls: .temp/Payload/Snapchat.app/Frameworks/_: No such file or directory

that is what the problem is can someone help?

**Comment by Defying** [comment]
`[:black_nib: ] Codesigning Plugins and Frameworks with certificate ""`

it appears you don't have the iPhone Developer certificate installed.

try this: https://www.youtube.com/watch?v=MDhXQ33Gqzg

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
