### ISSUE TITLE
Stuck 📦 ] Extracting SnapPlus usage: mv [-f | -i | -n] [-v] source target        mv [-f | -i | -n] [-v] source ... directory usage: mv [-f | -i | -n] [-v] source target        mv [-f | -i | -n] [-v] source ... directory

### ISSUE THREAD

**Issue by pocadot99** [Defying/TweakPatcher#27]

**Comment by Defying** [comment]
post your tweakpatcher.log

**Comment by pocadot99** [comment]
![screen shot 2016-04-12 at 02 47 06](https://cloud.githubusercontent.com/assets/18395474/14447570/09f4b4fc-0059-11e6-91c4-b231c6dba573.png)

**Comment by pocadot99** [comment]
![screen shot 2016-04-12 at 02 49 59](https://cloud.githubusercontent.com/assets/18395474/14447617/4b110472-0059-11e6-9e86-a938f6e0b0dd.png)

**Comment by pocadot99** [comment]
can you do me a favour @Defying  could you upload the cracked snapchat onto the internet so its easier?

**Comment by Defying** [comment]
@pocadot99 not going to do that for obvious reasons. the first result for "snapchat ipa" on google will work.

also, you didn't actually post your tweakpatcher.log. it's in the same directory as the patcher script

**Comment by Naman12** [comment]
I have the same problem @Defying 
Can you please help me w that?

![screen shot 2016-04-13 at 1 18 06 pm](https://cloud.githubusercontent.com/assets/18436617/14486404/335e2338-017a-11e6-90af-4948ff9f9709.png)

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
