### ISSUE TITLE
Tweaks not showing

### ISSUE THREAD

**Issue by ktsharma** [Defying/TweakPatcher#28]
i have done all the steps and i have gotten snapchat onto my device. But after i login and clear it out of my multitasking and go back in. None of the tweaks load. If anyone could pls help it would mean a lot

**Comment by Defying** [comment]
post your tweakpatcher.log

**Comment by ktsharma** [comment]
I am not able to send my tweakpatcher.log the file type is not supported @Defying

**Comment by Defying** [comment]
compress it first

**Comment by ktsharma** [comment]
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/214162/tweakpatcher.log.zip)

@Defying

**Comment by Defying** [comment]
@ktsharma you forgot to press Enter in Terminal after opening Snapchat.

**Comment by ktsharma** [comment]
should i press enter after the first time opening or the second? @Defying

**Comment by Defying** [comment]
it shouldn't matter

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
