### ISSUE TITLE
[❌ ] Failed to build ios-deploy. Check tweakpatcher.log for more information.

### ISSUE THREAD

**Issue by bobweaty** [Defying/TweakPatcher#29]

**Comment by Defying** [comment]
post your tweakpatcher.log

**Comment by scrazel** [comment]
[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/214173/tweakpatcher.log.zip)

**Comment by sinanilker** [comment]
Same deal here :( [❌ ] Failed to build ios-deploy. Check tweakpatcher.log for more information.
!
[screen shot 2016-04-13 at 11 27 10 pm](https://cloud.githubusercontent.com/assets/18450265/14508258/4abf1758-01cf-11e6-913f-3789f2a2af3c.png)

[tweakpatcher.log.zip](https://github.com/Defying/TweakPatcher/files/217898/tweakpatcher.log.zip)

**Comment by sinanilker** [comment]
Make sure that you open the xcode, write the passcode and xcode will begin the install its components then try steps again

**Comment by scrazel** [comment]
I got it to work eventually after deleting and redownloading everything twice lol, I was doing the same thing every time and it wasn't my first time doing it either I had done it on two other phones before hand with no problems

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
