### ISSUE TITLE
Stopped at [📥 ] Downloading libuasharedtools when doing all the steps right?! Help

### ISSUE THREAD

**Issue by James126788** [Defying/TweakPatcher#30]

**Comment by Defying** [comment]
is it still stuck there?

**Comment by James126788** [comment]
Yes

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
