### ISSUE TITLE
Failed to sign Snapchat.app with entitlements.xml

### ISSUE THREAD

**Issue by HauntedTony** [Defying/TweakPatcher#32]
Sorry to bother but I've looked through all of the other people's solutions and tried them but i just can't find a fix to this problem! This is my first time using codes and stuff, but I tried doing the correct steps at least 20 times. I really do not know of any other solutions that i could try, and I feel really bad for asking, but I really need help.

**Comment by HauntedTony** [comment]
@Defying Sorry to bother but I've looked through all of the other people's solutions and tried them but i just can't find a fix to this problem! This is my first time using codes and stuff, but I tried doing the correct steps at least 20 times. I really do not know of any other solutions that i could try, and I feel really bad for asking, but I really need help.

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
