### ISSUE TITLE
failed to install snapchat.ipa to iOS device 

### ISSUE THREAD

**Issue by msharialha** [Defying/TweakPatcher#33]
everytime i do the same steps but it comes to me like this [❌ ] Failed to install Snapchat.app with entitlements.xml. Check tweakpatcher.log for more information.

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
