### ISSUE TITLE
xcode has valid iOS Development certificate

### ISSUE THREAD

**Issue by timeXway** [Defying/TweakPatcher#34]
xcode is telling me, your account already has a valid iOS Development certificate, and i have option to cancel and reset, and both won't work, it will just stop here, anyone can help?﻿

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
