### ISSUE TITLE
App crashes after launch, something to do with certificate?

### ISSUE THREAD

**Issue by SabboME** [Defying/TweakPatcher#35]
Everything is working fine until i am going to open the app. It just sends me out. 
When I am deleting my certificates and creates a new Xcode project I am getting this message.
 [http://i.imgur.com/JwjUj20.png](url)
I press "Reset" and the patcher runs.
Then it gives me this error.
[http://i.imgur.com/GVT20qN.png](url)
So basicly I have to reset my certificate everytime I delete them.
Do you think the crashing have something to do with the issue?
I have watched some youtube videos, and they don't get this message when deleting their certificate.

**Comment by SabboME** [comment]
My error logs:
{"app_name":"Snapchat","timestamp":"2016-04-13 18:33:35.35 +0200","app_version":"9.27.5","slice_uuid":"b3332a63-2d78-3f2f-86da-3652ed6db171","adam_id":0,"build_version":"9.27.5.0","bundleID":"com.toyopagroup.picaboo","share_with_app_devs":false,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 9.3.1 (13E238)","name":"Snapchat"}
Incident Identifier: 1C538AEE-5EB8-408B-AF42-572955009A53
CrashReporter Key:   893ff2407797c6f520404b86a2e0c65bfb6e548a
Hardware Model:      iPhone6,2
Process:             Snapchat [406]
Path:                /private/var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/Snapchat
Identifier:          com.toyopagroup.picaboo
Version:             9.27.5.0 (9.27.5)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2016-04-13 18:33:35.35 +0200
Launch Time:         2016-04-13 18:33:35.35 +0200
OS Version:          iOS 9.3.1 (13E238)
Report Version:      105

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000000e7ffdefe
Triggered by Thread:  0

Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: @executable_path/librocketb.dylib
  Referenced from: /var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/Snapchat
  Reason: no suitable image found.  Did find:
    /var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/librocketb.dylib: mmap() errno=1 validating first page of '/var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/librocketb.dylib'
    /private/var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/librocketb.dylib: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/librocketb.dylib'
  Dyld Version: 390.7

Binary Images:
0x7c000 - 0x182ffff Snapchat armv7  <b3332a632d783f2f86da3652ed6db171> /var/containers/Bundle/Application/3911DC31-F926-4572-8B65-514DBAB1D6E0/Snapchat.app/Snapchat
0x1fefc000 - 0x1ff23fff dyld armv7s  <d96d5b718d2b3c3bad7f17d4e8a3f049> /usr/lib/dyld

**Comment by JRaddd** [comment]
this same thing is happening to me as well anyone have a fix?

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
