### ISSUE TITLE
Possible digression in specific binaries

### ISSUE THREAD

**Issue by alexzielenski** [Defying/TweakPatcher#37]
In this issue I'm referring to this line here: https://github.com/Defying/TweakPatcher/blob/master/tweakpatcher.sh#L339

optool works by adding load commands into the extra space after the macho header. The presence of the blank space is undefined behavior which it depends on, i.e. sometimes there may not be enough space to inject 1 dependency, let alone 5.

My suggestion is to create one dylib that would just load the others so that you only need space for one load command in order for the operation to succeed.

I also suggest that instead of inserting "load" commands you use the "-c weak" option so that the process doesn't crash if the library cannot be found.

**Comment by ahzan** [comment]
n
