### ISSUE TITLE
❌ ] Outdated version of Xcode detected. This script requires Xcode 7+." | tee -a $LOGFILE 	 echo "Download Xcode from the Mac App Store." |

### ISSUE THREAD

**Issue by chasebehrend** [Defying/TweakPatcher#39]
i have the new Xcode from the app store its just a while back i downloaded a old version off the internet and now it keeps saying this even though I've deleted everything and re-downloaded

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
