### ISSUE TITLE
[❌ ] Snapchat.ipa not found or not readable (Error) :-(

### ISSUE THREAD

**Issue by LMNZ2K2** [Defying/TweakPatcher#5]
Please Help!
I've tried to install this Snapchat tweak and I followed the steps carefully and made no mistakes and received this error: [❌ ] Snapchat.ipa not found or not readable . Please help!
Thanks :-)

**Comment by liudayu** [comment]
You need to rename your cracked snapchat ipa file from internet to 'Snapchat.ipa'
![qq20160410-0 2x](https://cloud.githubusercontent.com/assets/8695302/14404494/10abd54a-febb-11e5-92c3-ac6def56582e.png)

**Comment by LMNZ2K2** [comment]
I tried that :-(

**Comment by LMNZ2K2** [comment]
Could you provide a link for the cracked snapchat file? Thanks :-)

**Comment by LMNZ2K2** [comment]
I downloaded it from VSHARE last time?

**Comment by liudayu** [comment]
Just google 'snapchat ipa download' and it should be the first result.

**Comment by nerdtron123** [comment]
Yes, vShare has it, you need to move it to the TweakPatcher folder and rename to Snapchat.ipa

Make sure Snapchat is already removed from the phone.

**Comment by Defying** [comment]
closing this issue, TweakPatcher is deprecated and no longer will be supported.

**Please use [PP Sideloader](https://github.com/eni9889/ppsideloader) to sideload SnapPlus (and more)**
