### ISSUE TITLE
None matching entitlements

### ISSUE THREAD

**Issue by Critter** [Defying/TweakPatcher#7]
Even when I try using a wildcard provision cert I have, I get the same error

`2016-04-09 15:34:31.246 ios-deploy[68336:5224000] [ !! ] Error 0xe8008016: The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
[❌ ] Failed to install Snapchat.ipa to iOS device. Check tweakpatcher.log for more information.`

any ideas?

**Comment by Defying** [comment]
haven't seen that before! not really sure what could be causing that. :neutral_face: 

are you using a custom provisioning profile in the arguments?

**Comment by Critter** [comment]
I've tried it with a profile in the arguments and without. Same error.

Because I have a wildcard provision profile, I do not need to "fix" any apps that I create.. they all use the same one. Your script doesn't go past looking for the profile in that case.

If I pass in my wildcard, your script /does/ find it.. and continues to the end, but I still get the same error..

**Comment by Defying** [comment]
I see.

It's likely because of your wildcard cert. I don't have one, but they probably work a lot differently compared to the free certs.

The only thing I can suggest is to make a new Apple ID, use it in Xcode, and use the free certificate it provides you.

**Comment by Critter** [comment]
I ended up having to delete my business account out of xcode, and then delete my 2 certs in keychain. Once I had only my free one it worked..
