### ISSUE TITLE
AppPlus.dylib

### ISSUE THREAD

**Issue by marcosanchezz** [Defying/TweakPatcher#9]
I have no idea why this is happening. Ive copy and pasted both the log and the terminal code

[📱 ] Open Snapchat on your iOS device!
You may need to "Trust" your Apple ID in Settings/General/Device Management.
Once Snapchat is open, press Enter.

[🔎 ] Finding Container UUID
[🔎 ] Found Container UUID: 850A2BB8-825C-4226-8368-5B4378EB6EFA
[🔎 ] 850A2BB8-825C-4226-8368-5B4378EB6EFA -> 38353041324242382d383235432d343232362d383336382d354234333738454236454641
[💉 ] Patching AppPlus.dylib with new Container UUID
[❌ ] Failed to patch AppPlus.dylib. Check tweakpatcher.log for more information.

**THE LOG**

[📱 ] Open Snapchat on your iOS device!
You may need to "Trust" your Apple ID in Settings/General/Device Management.
[🔎 ] Finding Container UUID
[....] Waiting for iOS device to be connected
[....] Using iPhone 6 (GSM) 'iPhone' (c628e64d5afc8b718efbeb45cf9fb1880a62686d).
/Documents/container-uuid
[🔎 ] Found Container UUID: 850A2BB8-825C-4226-8368-5B4378EB6EFA
[🔎 ] 850A2BB8-825C-4226-8368-5B4378EB6EFA -> 38353041324242382d383235432d343232362d383336382d354234333738454236454641
[💉 ] Patching AppPlus.dylib with new Container UUID
File cannot be found
[❌ ] Failed to patch AppPlus.dylib. Check tweakpatcher.log for more information.

**Comment by Defying** [comment]
is there an `AppPlus.dylib` in `patch/`?

**Comment by marcosanchezz** [comment]
@Defying No there isnt

**Comment by marcosanchezz** [comment]
@Defying is there anyway you could upload the file?

**Comment by Defying** [comment]
it should be there...

can you post your tweakpatcher.log?

**Comment by marcosanchezz** [comment]
[👻 ] Tweak Patcher for jailed iOS devices v0.2
[🔌 ] by Defying / @dvfying
[💻 ] GitHub: https://github.com/Defying/TweakPatcher
[💻 ] Xcode 7+ detected.
[💯 ] Checking for required dependencies...
[👍 ] All dependencies found.
[📱 ] Waiting up to 5 seconds to detect an iOS device..
[....] Waiting up to 5 seconds for iOS device to be connected
[....] Found iPhone 6 (GSM) 'iPhone' (c628e64d5afc8b718efbeb45cf9fb1880a62686d) connected through USB.
[👍 ] Detected an iOS device!
[💯 ] Downloading dependencies for SnapPlus...
[📥 ] Downloading librocketbootstrap
[👍 ] Done.
[💯 ] Begin patching...
[💉 ] Patching librocketbootstrap
0x00004710: 27B
0x00010750: 27B
0x0001C750: 27B
0x000288D8: 27B
[💉 ] Patching libuasharedtools
0x00005198: 28B
0x00DB5410: 28B
[💉 ] Patching SnapPlus
File cannot be found
File cannot be found
File cannot be found
File cannot be found
File cannot be found
File cannot be found
[👍 ] Done.
[💯 ] Waiting on com.toyopagroup.picaboo-47719543-9981-47CB-8FA8-98DC91D4A8F0 provisioning profile to be created...

**Comment by marcosanchezz** [comment]
The problem was that my network firewall was blocking the download of one of the files. After I unblocked it worked perfectly. Thank you for responding!
